language: java
jdk:
- openjdk8
dist: bionic
addons:
  apt:
    packages:
      - python3
      - python3-pip
before_install:
- pip3 install --upgrade --user pip setuptools wheel
- pip3 install -U --user six numpy mock grpcio grpcio-tools
script:
- alias python=python3
- python --version
- cd deep-learning-on-flink && mvn -DskipITs=true clean package
branches:
  except:
  - appveyor