language: java
jdk:
- openjdk8
dist: bionic
before_install:
- pip install --upgrade --user pip setuptools wheel
- pip install -U --user six numpy mock grpcio grpcio-tools
script:
- cd deep-learning-on-flink && mvn -DskipITs=true clean package
branches:
  except:
  - appveyor