language: java
jdk:
- openjdk8
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_script:
- pip3 install -U --user pip six numpy wheel mock grpcio grpcio-tools
- ln -sf `which python3` /usr/local/bin/python
- ln -sf `which pip3` /usr/local/bin/pip
script:
- mvn -DskipITs=true clean package
branches:
  except:
  - appveyor